szokodiakos/typegoose

src/prop.ts

Hi. Thank you for the awesome library.
I'm not very experienced with TS and I've spent a lot of time for that problem:
```
TypeError: Type is not a constructor
at baseProp (typegoose/lib/prop.js:68:20)
```
So, I decided that it's very helpful to show this error if emitDecoratorMetadata isn't enabled.

Show error if emitDecoratorMetadata isn't enabled

---

.travis.yml
package.json

Ensure we can still run with the oldest dependencies that we say we can
run with.
This is expected to fail until typescript is updated to 2.3.0 in package.json.

Check that we don't depend on newer dependencies

---

src/prop.ts

This PR fix the issue with prop decorators that returned an object which was treated as property descriptor. This was overwriting property, so other decorator-based libs like `class-transformer` couldn't work at all.

Fix returning invalid prop descriptor by decorators

---

.travis.yml
README.md
package-lock.json
package.json
src/test/index.test.ts
src/test/utils/mongoConnect.ts

At the moment, _mongoose_ and _reflect-metadata_ are listed as depencies. This can lead to several problems.
Starting with version 5.0, _mongoose_ and _reflect-metadata_ have been moved to peer dependencies, so the users are required to install these packages themselves.

Move mongoose and reflect-metadata to peer depencencies

---

src/test/index.test.ts
src/test/models/car.ts
src/utils.ts
tslint.json

fixes https://github.com/szokodiakos/typegoose/issues/114 by simply adding `Decimal128` as primitive type. Since it is perfectly supported by mongoose it seems to work.

Add Decimal128 as primitive type.

---

README.md
src/prop.ts
src/test/index.test.ts
src/test/models/person.ts

Adds support for custom validators. Sync/async functions or regex.
Example (added to README.md):
```typescript
// you have to get your own `isEmail` function, this is a placeholder
@prop({ validate: (value) => isEmail(value)})
email: string;
// or
@prop({ validate: (value) => { return new Promise(res => { res(isEmail(value)) }) })
email: string;
// or
@prop({ validate: { 
validator: val => isEmail(val), 
message: `{VALUE} is not a valid email`
}})
email: string;
// or
@prop({ validate: /\S+@\S+\.\S+/ })
email: string;
// you can also use multiple validators in an array.
@prop({ validate: 
[
{ 
validator: val => isEmail(val), 
message: `{VALUE} is not a valid email`
}, 
{
validator: val => isBlacklisted(val), 
message: `{VALUE} is blacklisted`
}
]
})
email: string;
```

Support for custom validators

---

package.json

This reduces package size from ~500kB unpacked to ~40kB unpacked.
There is no reason to include tests, typescript source and options, travis config and IDE settings in distribution package that is uploaded to npm.

reduce package size by including only lib directory (without tests) 

---

src/errors.ts

I got this message in the console because I forgot to enable `emitDecoratorMetadata`, and noticed that there were a few spaces missing.

Add spaces to the message of NoMetadataError

---

README.md
package-lock.json
src/index.ts
src/test/index.test.ts
src/test/models/rating.ts
src/test/utils/mongoConnect.ts
src/typegoose.ts

I have implemented adding of indexes to schema. This allows compound indexes and other index types (eg. GeoJSON). See README.md changes for example usage.
This PR solves following issues:
[#45](https://github.com/szokodiakos/typegoose/issues/45), [#141](https://github.com/szokodiakos/typegoose/issues/141), [#43](https://github.com/szokodiakos/typegoose/issues/43)
Implementation uses `reflect-metadata` to save index options to class and not as `./data` global. I believe this is better approach since this way more than one schema with the same name can be instantiated.

add @index class decorator

---

.travis.yml
src/prop.ts
src/test/index.test.ts
src/test/models/user.ts

Creating the mongoose configuration for array enums are wrong. the whole config object is not needed to be wraped in an array, instead just wrap the `Type` with an array.
Fixes #202

fix(): config for array enums must be set correctly

---

README.md

- Align the code snippets inside the bulleted paragraphs
- minor typo
- remove a duplicate code section about `unique`

Formatting improvements and minor typo

---

package-lock.json
package.json

The previous pull request did not include updates to package-lock.json
bumped the version to reflect the changes to "version": "5.5.1"
=== npm audit security report ===                        
found 0 vulnerabilities
in 253 scanned packages

 Bumped to version: 5.5.1 after updating lodash dependencie

---

src/hooks.ts

When defining hooks on Model middleware functions (afaik only `insertMany`) moongoose will supply the docs as second argument. See https://github.com/Automattic/mongoose/pull/5116
This should enable it for Typegoose aswell.

Better support for Model middleware hooks

---

src/prop.ts
src/test/index.test.ts
src/test/models/virtualprop.ts
src/typegoose.ts

- adding #271
- with tests
- and an "overwrite" value, to not set `.get & .set` only `.virtual()`
fixes #131 
example:
```ts
import { ObjectID } from "bson";
import * as mongoose from "mongoose";
import { prop, Ref, Typegoose } from "./typegoose";
class User extends Typegoose {
@prop({ required: true })
public name!: string;
@prop({ foreignField: "user", localField: "_id", ref: "Posts", justOne: false, overwrite: true })
public get posts() {
console.log("args", arguments);
return this.posts;
}
}
class Posts extends Typegoose {
@prop({ required: true, ref: User })
public user!: Ref<User>;
@prop()
public message!: string;
}
const PostsModel = new Posts().getModelForClass(Posts);
const UserModel = new User().getModelForClass(User);
(async () => {
mongoose.set("debug", true);
await …
```

Add virtual populate options

---

src/typegoose.ts

When using typegoose its not always possible to plugin a custom promise library for mongoose in some projects (e.g. Bluebird) - [the line here](https://github.com/szokodiakos/typegoose/blob/master/src/typegoose.ts#L6) means that the order of importing typegoose matters, and its not always possible without adding complexity.
Now that mongoose [uses native promises by default](http://thecodebarbarian.com/introducing-mongoose-5.html) it should be possible to remove this safely.

Remove the setting of mongoose.Promise

---

.gitignore
.npmignore
.vscode/tasks.json
package-lock.json
package.json
src/errors.ts
src/prop.ts
src/test/enums/genders.ts
src/test/hookTests/dummy.ts
src/test/hookTests/hooks.test.ts
src/test/hookTests/hooktestModel.ts
src/test/index.test.ts
src/test/models/PersistentModel.ts
src/test/models/car.ts
src/test/models/inventory.ts
src/test/models/job.ts
src/test/models/nested-object.ts
src/test/models/person.ts
src/test/models/rating.ts
src/test/models/user.ts
src/test/models/virtualprop.ts
src/typegoose.ts
src/utils.ts
tsconfig.json
tslint.json

Changes:
- removing extra vscode task
- adding "watch" to the npm scripts
- adding tsbuildinfo / incremental to compile faster
- adding "removeComments" to minimize output
- TSLint Changes:
- removing unnecessary options
- adding/modifing options to get a more consistent coding style
- apply changes from tslint
And the Changes to fix #311 mentioned Issues

Fixing the issues i mentioned in #311 & more consistent Coding-Style

---

src/hooks.ts

as the Title says  
I'm making an extra pr, because i dont know if this line should be kept, otherwise, free-to-merge

Remove unused type in hooks.ts

---

package-lock.json
test/config_default.json
test/utils/config.ts
test/utils/mongooseConnect.ts

- Reworked the config to be included again, to investigate the database after running a test / to just execute it on an remote database
- Modified the config & connect so, that the In-Memory option is default on, but can be disabled & changed
- Audit fix for mocha

Re-Work of the config with In-Memory

---

.github/CONTRIBUTING.md
.github/ISSUE_TEMPLATE/feature parity.md
.github/ISSUE_TEMPLATE/feature.md
.github/ISSUE_TEMPLATE/question.md
.gitignore
.travis.yml
README.md
package-lock.json
package.json
src/data.ts
src/hooks.ts
src/index.ts
src/method.ts
src/plugin.ts
src/prop.ts
src/typegoose.ts
src/utils.ts
test/models/person.ts
test/utils/config.ts
test/utils/mongooseConnect.ts

- includes #92 
---
- adding typedoc as a dev-depdendency
- adding script to generate the docs
- adding "doc/" to the "clean" script
- making `npm audit` not failing the build (it just reports it)
---
- remove TransformStringOptions from ValidateStringOptions
- modify person model to a bit cleaner style
- config
- config: adding a small check if config.Memory is enabled
- config: moving "import" to the top of the file, like in any other file
---
- adding a note to CONTRIBUTING
- adding template to request a feature
- adding minor fixes to other Issue Templates
---
- adding docs for:
- prop
- plugin
- method
- index
- utils
- hooks
- data (some)
---
(closes #92)

Docs, typedoc

---

src/utils.ts

- removes the typeguards from `utils.ts`, because there is an extra file for it named `typeguards.ts`
it got accidentally added in cf75bd0fc10b3d4909fd838c6c634b111229762c

Fix the double typeguards
