package.json

Fixes https://github.com/szokodiakos/typegoose/issues/22

Fix typescript compilation

---

src/typegoose.ts

Removed the reserved ID, tests still pass

---

README.md
package.json
src/test/index.test.ts
src/test/models/job.ts
src/test/models/user.ts

Fixed the examples for sub documents (Job) Closes #30

Test Job class changed, added new test and user instance methods

---

package.json
src/data.ts
src/prop.ts
src/test/index.test.ts
src/test/models/user.ts
src/typegoose.ts
src/utils.ts
tsconfig.json

Feature: ClassType reflection capabilities

---

src/test/index.test.ts
src/test/models/person.ts
src/typegoose.ts

Extension of the method 'getModelForClass' of the class 'Typegoose' to achieve inheritance of the schema. Unit tests (and models) have been added. Can you please check my fork and if you have comments please let me know. I would be very happy if you would merge my fork.

Schema inheritance

---

README.md
src/typegoose.ts

Hi Akos,
thank you for your great project.
Since we use Typegoose both in our core module and in the respective project modules, we need the possibility to overwrite existing models.
For example, we have a rudimentary user model in the core and would like to replace it with a more complex user model from the respective project. Since the behaviour in the core should change, the model must be able to be overwritten in the core.
This was not possible before, because only a reading function was available, which only created a new model if it did not exist before.
Best regards
Kai

Added function setModelForClass to allow models to be overwritten

---

.editorconfig
.vscode/launch.json
.vscode/tasks.json
src/prop.ts
src/test/index.test.ts
src/test/models/nested-object.ts
src/utils.ts

Hello Akos,
thanks for your great project. Since we use Typgoose in our project, we need the ability to save nested  documents (plain json) in our document.
I have made a small change in the 'prop' decorate and written tests for it. It would be nice if you could look at this and merge it together.
Best regards
Uwe

Nested documents

---

src/prop.ts
src/test/index.test.ts
src/test/models/job.ts

Allow supressing _id for subdocuments

---

src/hooks.ts
src/test/hookTests/dummy.ts
src/test/hookTests/hooks.test.ts

Despite a lack of documentation about it, there exists an updateMany hook in Mongoose. This PR just adds support for it

Add support for updateMany hook

---

README.md
src/hooks.ts
src/prop.ts
src/test/hookTests/dummy.ts
src/test/hookTests/hooks.test.ts
src/test/index.test.ts
src/test/models/car.ts
src/test/models/person.ts

This can be useful when working with a mixed ts/js project

Updated 'ref' parameter to allow population by string

---

package.json

Some vulnerabilities require your attention to resolve: Prototype Pollution in lodash Patched in  ">=4.17.11"

correction lodash in  dependencies

---

README.md
package-lock.json
package.json

tanks to @MihkelBaranov (#104)

Update version for next release

---

README.md

[Doc] add a note to InstanceType

---

src/prop.ts

Fixes #296
Fixes #301
Signed-off-by: Chris Lahaye <dev@chrislahaye.com>

Add type property to array schema to fix array defaults

---

README.md
src/prop.ts
src/test/index.test.ts
src/test/models/inventory.ts

This PR implements #310 as well as adding unit tests to cover.

Support for mongoose refPath, see #310

---

src/prop.ts
test/index.test.ts
test/models/select.ts

- adding the select property
- adding tests for the select property
- adding jsdoc to select, and other properties
closes #197

Adding @prop({select}) with tests & some jsdoc

---

.github/CONTRIBUTING.md
.github/ISSUE_TEMPLATE/bug.md
.github/ISSUE_TEMPLATE/feature parity.md
.github/ISSUE_TEMPLATE/question.md
.github/PULL_REQUEST_TEMPLATE/Docs.md
.github/PULL_REQUEST_TEMPLATE/Enhancement.md
.github/PULL_REQUEST_TEMPLATE/Feature.md
.github/SECURITY.md
LICENSE

- adding Templates
- adding MIT License (as Specified in package.json)
i think the following labels must be created for this pull request:
- docs
- feature
- parity
Please give feedback on what could be added (or removed) from these templates
(and please say if i got any writing mistakes, thanks)
Note: I force push & rebase to keep it only one commit

Adding some Templates & MIT License

---

.github/ISSUE_TEMPLATE/bug.md

*Look in the "changes" tab to see what is added in the template*

Include more in a Bug Template

---

README.md
src/prop.ts
test/index.test.ts
test/models/internet-user.ts

- add @mapProp
- add tests for @mapProp
- add @mapProp README docs
- polish & rebase of #284
closes #284
closes #274 
differences:
- resolved merge conflicts
- ran up-to-date-tests & tslint --fix
- added tsdoc for `@mapProp`
- moved "side-note.ts"'s class into "internet-user.ts"

Add @mapProp for Maps with tests

---

src/typegoose.ts
src/typeguards.ts
test/index.test.ts
test/models/userRefs.ts
test/tests/typeguards.test.ts

isDocument and isDocumentArray type guards

---

README.md
src/prop.ts
test/index.test.ts
test/models/alias.ts

- add @prop({ alias })
- add tests for alias
- add tsdoc & example for alias
- add readme doc for alias
closes #166 
fixes #263 
PS: i suggest making a new release when this is merged

Add mongoose alias prop

---

.github/PULL_REQUEST_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE/docs.md
.github/PULL_REQUEST_TEMPLATE/enhancement.md
.github/PULL_REQUEST_TEMPLATE/feature parity.md
.github/PULL_REQUEST_TEMPLATE/feature.md
.github/PULL_REQUEST_TEMPLATE/fix.md
README.md

- renames the PR-templates to lowercase, like issue templates
- adds a bit text to the templates
- adds feature-parity
- adds fix (for bug fixes and pr fixes)
- add more requirements to the README's "## Requirements"
- replace "```typescript" with "```ts"
- added README doc for "refPath"
- added README doc for "itemsRefPath"
- added a todo to the README
- implements #232
changes, because currently there is no option to apply a template for a PR, only one default one
closes #232

"Fix" github PR templates

---

README.md
src/hooks.ts
test/hookTests/hooktestModel.ts
test/tests/hooks.test.ts

- adding REGEXP as method name for hooks
- adding tests for REGEXP as method for hooks
fixes #303

Adding REGEXP to hook method names

---

src/index.ts
test/index.test.ts
test/models/indexweigths.ts

- adding index options weigths
- adding test for weights option
fixes #298 
PS: sorry for so many PR's in just 24 hours ...

Adding @index({}, {weights:{}})

---

.github/CONTRIBUTING.md
.github/Notes to Maintainers.md
.github/SECURITY.md
README.md
package.json

- modify CONTRIBUTING to include how to structure commits
- modify package.json Versions to include majors, where it should be included
- modify README to include how this package is Versioned
- adding "Notes to Maintainers" to know how the processes work
@Ben305 i would need to know which version of the merge method is / should / will be used and to confirm that the versioning is correct

Adding Maintainer notes

---

src/prop.ts

this commit should get reverted if https://github.com/Automattic/mongoose/issues/8034 gets fixed!
try to use an template, found at .github/PULL_REQUEST_TEMPLATE/
[here](https://github.com/szokodiakos/typegoose/tree/master/.github/PULL_REQUEST_TEMPLATE)
please dont forget to click on raw, and copy that, not the already "compiled" one
implements a fix for #362, but dosnt close it, because of https://github.com/Automattic/mongoose/issues/8034

[HOTFIX] Implement a hack for ObjectID

---

README.md

- adds note that typegoose cant be used with multiple classes of the same name
fixes szokodiakos#376

Add Note for szokodiakos#376

---

README.md

Add a note that Typegoose uses mongoose strict everywhere

Adding note that typegoose uses mongoose strict
